using System.Linq;
using Json.Masker.Abstract;

namespace Json.Masker.IntegrationSample.Models;

/// <summary>
/// Represents a customer record within the integration sample data set.
/// </summary>
public class Customer
{
    /// <summary>
    /// Gets or sets the unique identifier for the customer.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the customer's first name.
    /// </summary>
    [Sensitive]
    public string FirstName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the customer's last name.
    /// </summary>
    [Sensitive]
    public string LastName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the customer's email address.
    /// </summary>
    [Sensitive(MaskingStrategy.Email)]
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the customer's phone number.
    /// </summary>
    [Sensitive("***-***-####")]
    public string PhoneNumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the customer's national identification number.
    /// </summary>
    [Sensitive(MaskingStrategy.Ssn)]
    public string NationalId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the customer's loyalty program number.
    /// </summary>
    [Sensitive("LOY-***-####")]
    public string LoyaltyNumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the billing address associated with the customer.
    /// </summary>
    [Sensitive]
    public Address BillingAddress { get; set; } = new();

    /// <summary>
    /// Gets or sets the shipping address associated with the customer.
    /// </summary>
    [Sensitive]
    public Address ShippingAddress { get; set; } = new();

    /// <summary>
    /// Gets or sets the date when the customer registered.
    /// </summary>
    public DateTimeOffset RegisteredAt { get; set; }

    /// <summary>
    /// Gets or sets the customer's status.
    /// </summary>
    public CustomerStatus Status { get; set; }

    /// <summary>
    /// Gets or sets the collection of orders associated with the customer.
    /// </summary>
    public List<Order> Orders { get; set; } = new();

    /// <summary>
    /// Gets the total revenue generated by the customer's orders.
    /// </summary>
    public decimal LifetimeValue => Orders.Sum(order => order.Total);

    /// <summary>
    /// Gets the full name for the customer.
    /// </summary>
    public string FullName => $"{FirstName} {LastName}".Trim();
}
