style: github
template: CHANGELOG.tpl.md
info:
  title: "CHANGELOG"
  repository_url: https://github.com/myarichuk/Json.Masker
options:
  commits:
    sort: "ASC"
  commit_groups:
    title_maps:
      feat: "Features"
      fix: "Bug Fixes"
      perf: "Performance"
      refactor: "Refactoring"
      docs: "Documentation"
      test: "Tests"
      ci: "CI"
      chore: "Chores"
  header:
    pattern: "^(\\w*)(?:\\((.*)\\))?:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
