using Json.Masker.Abstract;
using Json.Masker.IntegrationSample.Models;

namespace Json.Masker.IntegrationSample.Models.Dtos;

/// <summary>
/// Represents a lightweight view of a customer for list pages.
/// </summary>
public class CustomerOverview
{
    /// <summary>
    /// Gets the unique identifier of the customer.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Gets the customer's full name.
    /// </summary>
    [Sensitive]
    public string FullName { get; init; } = string.Empty;

    /// <summary>
    /// Gets the customer's email address.
    /// </summary>
    [Sensitive(MaskingStrategy.Email)]
    public string Email { get; init; } = string.Empty;

    /// <summary>
    /// Gets the customer's phone number.
    /// </summary>
    [Sensitive("***-***-####")]
    public string PhoneNumber { get; init; } = string.Empty;

    /// <summary>
    /// Gets the customer's national identification number.
    /// </summary>
    [Sensitive(MaskingStrategy.Ssn)]
    public string NationalId { get; init; } = string.Empty;

    /// <summary>
    /// Gets the customer's loyalty program number.
    /// </summary>
    [Sensitive("LOY-***-####")]
    public string LoyaltyNumber { get; init; } = string.Empty;

    /// <summary>
    /// Gets the customer's current status.
    /// </summary>
    public CustomerStatus Status { get; init; }

    /// <summary>
    /// Gets the timestamp when the customer registered.
    /// </summary>
    public DateTimeOffset RegisteredAt { get; init; }

    /// <summary>
    /// Gets the total number of orders associated with the customer.
    /// </summary>
    public int OrderCount { get; init; }

    /// <summary>
    /// Gets the total revenue generated by the customer.
    /// </summary>
    public decimal LifetimeValue { get; init; }
}
